version: '3.8'

services:
  jobmanager:
    build:
      context: ./jobmanager
    ports:
      - '8081:8081'
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    command: jobmanager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/overview"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  taskmanager:
    build:
      context: ./taskmanager
    depends_on:
      jobmanager:
        condition: service_healthy
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    command: taskmanager
    healthcheck:
      test: ["CMD", "nc", "-z", "jobmanager", "6123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
