spring:
  application:
    name: streaming-processing

kafka:
  bootstrap-servers: localhost:9092
  topic: data-topic
  group-id: flink-consumer

logging:
  level:
    com.example: INFO
    org.apache.flink: INFO

flink:
  job:
    name: kafka-stream-consumer
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: 3
    restart-strategy.fixed-delay.delay: 10s 