spring:
  application:
    name: csv-processor

kafka:
  bootstrap:
    servers: kafka:9092
  client:
    id: producer
  topic: data-topic

file:
  source:
    path: /app/mock_data


logging:
  level:
    root: INFO
    com.example: INFO
    org.apache.flink: INFO
    org.apache.kafka: INFO
    org.springframework: INFO 